---
- name: checking Ubuntu version
  fail:
    msg: Ubuntu version to old, minium version is 24.04
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '24.04'

- name: include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

# check first if file exists in the main files directory
- name: handling containers.conf
  when: lookup('ansible.builtin.fileglob', podman_containers_conf) != []
  block:
    - name: copy containers.conf
      copy:
        src: "{{ podman_containers_conf }}"
        dest: /etc/containers/containers.conf
        mode: '0644'
      notify: restart podman.socket

# get or create podman user
- name: setup podman user
  tags: user
  include_tasks: user.yml

# define users dir for systemd configs
- name: define destination directory
  tags: dev
  ansible.builtin.set_fact:
    __podman_systemd_users_dir: "/etc/containers/systemd/users/{{ podman_user_uid }}/"
    cachable: true

# copy over available quadlets
# variable: podman_applications
- name: install quadlets
  when: podman_applications != {}
  tags: dev
  block:
    - name: ensure systemd users dir exists
      file:
        path: "{{ __podman_systemd_users_dir | dirname }}"
        state: directory
        owner: "{{ podman_user }}"
        group: "{{ podman_group }}"
        mode: "0755"

    - name: "copy quadlets for {{ item.key }}"
      copy:
        src: "quadlets/{{ item.key }}/"
        dest: "{{ __podman_systemd_users_dir }}."
        mode: '0644'
      notify: systemd user reload
      loop: "{{ podman_applications | dict2items }}"
