---
# tasks file for ruby

- name: Install basic packages
  dnf:
    name: "{{ podman_packages }}"
    state: present

- name: All packages installed.
  debug:
    msg: Packages have been successfully installed
