---
- name: restart podman.socket
  ansible.builtin.service:
    name: podman.socket
    state: restarted

- name: systemd user reload
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
  become: true
  become_user: "{{ podman_user }}"
